# Generated by Django 2.2 on 2020-06-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='客户端号')),
                ('receiver_mobile', models.IntegerField(verbose_name='分数')),
            ],
            options={
                'db_table': 'client_ranking',
            },
        ),
    ]
